app_name: outway
listen:
  udp: :53
  tcp: :53
upstreams:
- name: cloudflare-doh
  address: https://cloudflare-dns.com/dns-query
  weight: 1
- name: cf-ipv4
  address: udp://1.1.1.1:53
  weight: 1
- name: cf-ipv6
  address: udp://[2606:4700:4700::1111]:53
  weight: 1
- name: google
  address: udp://8.8.8.8:53
  weight: 1
- name: opendns
  address: udp://208.67.222.222:53
  weight: 1
rule_groups:
- name: YouTube & Google Services
  description: Route YouTube and Google services through specific interface
  via: utun4
  patterns:
  - "*.youtube.com"
  - "*.googlevideo.com"
  - "*.ytimg.com"
  - "*.googleapis.com"
  - "*.googleusercontent.com"
  pin_ttl: true
- name: Social Media
  description: Social media platforms routing
  via: utun4
  patterns:
  - "*.instagram.com"
  - "*.facebook.com"
  - "*.twitter.com"
  - "*.x.com"
  - "*.tiktok.com"
  - "*.snapchat.com"
  pin_ttl: true
- name: Streaming Services
  description: Video streaming platforms
  via: utun4
  patterns:
  - "*.netflix.com"
  - "*.hulu.com"
  - "*.disney.com"
  - "*.amazon.com"
  - "*.twitch.tv"
  pin_ttl: true
- name: Development Tools
  description: Development and version control services
  via: utun3
  patterns:
  - "*.github.com"
  - "*.gitlab.com"
  - "*.bitbucket.org"
  - "*.docker.com"
  - "*.npmjs.org"
  pin_ttl: true
- name: Blocked Domains
  description: Blocked malicious domains
  via: lo0
  patterns:
  - "*.malware.com"
  - "*.phishing-site.com"
  - "*.ads-tracker.com"
  pin_ttl: true
history:
  enabled: true
  max_entries: 10000
log:
  level: info
cache:
  enabled: true
  max_entries: 20000
http:
  enabled: true
  listen: 127.0.0.1:47823
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 2m0s
  max_header_bytes: 1048576
# Update configuration
# You can also update manually using: outway self-update
update:
  enabled: true
  include_prerelease: false
hosts:
- pattern: localhost
  a:
  - 127.0.0.1
  ttl: 60
- pattern: "*.example.com"
  a:
  - 127.0.0.1
  ttl: 60
